### ISSUE TITLE
403 forbiden

### ISSUE THREAD

**Issue by emiliien** [YunoHost-Apps/digitools_ynh#2]
Salut,
aprs l'installation de digitool, j'ai bien l'affichage des tuiles d'outils ( roue de la fortune, cartes ,etc) mais lorsque je sélectionne un choix, j'ai une erreur 403 forbiden.
Je vais essayer d'aller récupérer les logs d'nginx dans la soirée. Là je suis sur mon téléphone 😑

**Comment by TheNomad11** [comment]
Same here, was not able to find anything useful in the logs either

**Comment by emiliien** [comment]
2022/04/02 17:45:44 [error] 21305#21305: *2978867 directory index of "/var/www/digitools/roue/" is forbidden, client: XX.XX.XX.XX, server: mondomaine.fr, request: "GET /digitools/roue/ HTTP/2.0", host: "mondomaine.fr", referrer: "https://mondomaine.fr/digitools/"
only lgs i have

**Comment by pagiraud** [comment]
Indeed, I can reproduce this behavior…
Thanks for the report. I’ll investigate as soon as I can.

**Comment by pagiraud** [comment]
If you know how to do this, could you please modify the appropriate nginx configuration file? It should be '/etc/nginx/conf.d/your.domain.tld.d/digitools.conf'.
Uncomment the line 'index index.html index.php;'
This solved the problem for me. Tell me if it’s ok for you so I can make a PR.

**Comment by emiliien** [comment]
Great ! it's works fine ! 
Thx a lot .
LMFao  i saw that yesterday and i don't know why i forgot to reload nginx -_-' xD 
EDIT  strange ..... tools work independently but first page dosen't work anymore ..... 
NEW EDIT : don't forget index.html ^^  it's aliveeeee ! aaalivvve !
